---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-app
data:
  mysql-password: RDN2JXBzMTIzNAo=
  mysql-root-password: RDN2JXBzMTIzNAo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flask-app
data:
  mysql-db-name: db
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: flask-app
  labels:
    name: mysql
  spec:
    container:
      - name: mysql
        image: mysql:8
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limit:
            cpu: 200m
            memory: 512Mi
        ports:
          - containerPort: 3306
            name: mysql-container
        env: 
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
          - name: MYSQL_DATABASE
            valueFrom:
               configMapKeyRef:
                name: mysql-config
                key: mysql-db-name
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: flask-app
spec:
  selector: 
    name: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql-container
      name: mysql
