---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: flask-app
  labels:
    name: mysql
  spec:
    container:
      - name: mysql
        image: mysql:8
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limit:
            cpu: 200m
            memory: 512Mi

          

